[server]
port = 10086
max_conn = 2048
affair_queue_capacity = 256
affair_queue_process_quantity = 16
affair_queue_process_interval = 50

[conn]
read_buffer_size = 1024

[cluster]
max_user = 100

[team]
max_user = 5

[user]
request_ttl = 5000
heartbeat_timeout = 5000
heartbeat_interval = 200